### ISSUE TITLE
Please improve comment writing.

### ISSUE THREAD

**Issue by jashkarangiya** [ketul-pandya/DSA_College#1]
Sir, I was going through your practical repo and I found out that the comment was not good enough to understand the purpose of your commit. For example: your comment: "proper github woring is on from onwards" could have been "Working on GitHub properly from now-onwards." Click [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ) to check the proper commenting formats.

**Comment by ketul-pandya** [comment]
Ya I can see that you are too worried and serious for me that why you had set the dancing video in 'click'.
